/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PlayContainer {
    }
    interface PlayContent {
    }
    interface PlaySlot {
    }
}
declare global {
    interface HTMLPlayContainerElement extends Components.PlayContainer, HTMLStencilElement {
    }
    var HTMLPlayContainerElement: {
        prototype: HTMLPlayContainerElement;
        new (): HTMLPlayContainerElement;
    };
    interface HTMLPlayContentElement extends Components.PlayContent, HTMLStencilElement {
    }
    var HTMLPlayContentElement: {
        prototype: HTMLPlayContentElement;
        new (): HTMLPlayContentElement;
    };
    interface HTMLPlaySlotElement extends Components.PlaySlot, HTMLStencilElement {
    }
    var HTMLPlaySlotElement: {
        prototype: HTMLPlaySlotElement;
        new (): HTMLPlaySlotElement;
    };
    interface HTMLElementTagNameMap {
        "play-container": HTMLPlayContainerElement;
        "play-content": HTMLPlayContentElement;
        "play-slot": HTMLPlaySlotElement;
    }
}
declare namespace LocalJSX {
    interface PlayContainer {
    }
    interface PlayContent {
    }
    interface PlaySlot {
    }
    interface IntrinsicElements {
        "play-container": PlayContainer;
        "play-content": PlayContent;
        "play-slot": PlaySlot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "play-container": LocalJSX.PlayContainer & JSXBase.HTMLAttributes<HTMLPlayContainerElement>;
            "play-content": LocalJSX.PlayContent & JSXBase.HTMLAttributes<HTMLPlayContentElement>;
            "play-slot": LocalJSX.PlaySlot & JSXBase.HTMLAttributes<HTMLPlaySlotElement>;
        }
    }
}
